#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LiveOthelloAndroid.Resource", IsApplication=true)]

namespace LiveOthelloAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int black_disc = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int buttonstyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int empty_disc = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int game = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int game_small = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_title_share_default = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int logo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int menu_info = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int menu_settings = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int menu_update = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int tournament_small = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int white_disc = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int btnGame = 2131099652;
			
			// aapt resource value: 0x7f060013
			public const int btnMenu = 2131099667;
			
			// aapt resource value: 0x7f06001e
			public const int btnMoveFirst = 2131099678;
			
			// aapt resource value: 0x7f060021
			public const int btnMoveLast = 2131099681;
			
			// aapt resource value: 0x7f060020
			public const int btnMoveNext = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int btnMovePrior = 2131099679;
			
			// aapt resource value: 0x7f060014
			public const int btnViewChange = 2131099668;
			
			// aapt resource value: 0x7f060006
			public const int cbNotificationSound = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int cbNotificationVibration = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int cbUseHamletApplet = 2131099656;
			
			// aapt resource value: 0x7f06001a
			public const int gameName = 2131099674;
			
			// aapt resource value: 0x7f060003
			public const int gamesspinner = 2131099651;
			
			// aapt resource value: 0x7f06001b
			public const int gridview = 2131099675;
			
			// aapt resource value: 0x7f060012
			public const int layoutButtons = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int layoutFlipper = 2131099669;
			
			// aapt resource value: 0x7f060019
			public const int layoutMain = 2131099673;
			
			// aapt resource value: 0x7f060005
			public const int layoutNews = 2131099653;
			
			// aapt resource value: 0x7f06001c
			public const int positionInfo = 2131099676;
			
			// aapt resource value: 0x7f060011
			public const int rbGamesEvery = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int rbGamesNone = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int rbGamesOne = 2131099664;
			
			// aapt resource value: 0x7f06000d
			public const int rbTournamentEvery = 2131099661;
			
			// aapt resource value: 0x7f06000b
			public const int rbTournamentNone = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int rbTournamentOne = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int rgGamesNotifications = 2131099662;
			
			// aapt resource value: 0x7f06000a
			public const int rgTournamentNotifications = 2131099658;
			
			// aapt resource value: 0x7f06001d
			public const int statusText = 2131099677;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int textView2 = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int textView3 = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int tournamentspinner = 2131099649;
			
			// aapt resource value: 0x7f060016
			public const int viewFlipper1 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int webView1 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int webView2 = 2131099672;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Settings = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ViewGame = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ViewGameNative = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int black = 2130968585;
			
			// aapt resource value: 0x7f04000d
			public const int button_first = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int button_last = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int button_next = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int button_prior = 2130968590;
			
			// aapt resource value: 0x7f040011
			public const int check_update = 2130968593;
			
			// aapt resource value: 0x7f040007
			public const int game_finished = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int game_menu = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int game_status = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int game_waiting_start = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int games = 2130968578;
			
			// aapt resource value: 0x7f04001e
			public const int games_notification = 2130968606;
			
			// aapt resource value: 0x7f04000b
			public const int live_status = 2130968587;
			
			// aapt resource value: 0x7f040014
			public const int new_game_notification = 2130968596;
			
			// aapt resource value: 0x7f04000c
			public const int new_move = 2130968588;
			
			// aapt resource value: 0x7f040013
			public const int new_tournament_notification = 2130968595;
			
			// aapt resource value: 0x7f040015
			public const int notification_alerts = 2130968597;
			
			// aapt resource value: 0x7f04001d
			public const int notification_every = 2130968605;
			
			// aapt resource value: 0x7f04001b
			public const int notification_none = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int notification_one = 2130968604;
			
			// aapt resource value: 0x7f040016
			public const int play_sound = 2130968598;
			
			// aapt resource value: 0x7f040021
			public const int progress_games = 2130968609;
			
			// aapt resource value: 0x7f04001f
			public const int progress_title = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int progress_tournaments = 2130968608;
			
			// aapt resource value: 0x7f040012
			public const int settings = 2130968594;
			
			// aapt resource value: 0x7f040018
			public const int show_lights = 2130968600;
			
			// aapt resource value: 0x7f04001a
			public const int tournament_notification = 2130968602;
			
			// aapt resource value: 0x7f040001
			public const int tournaments = 2130968577;
			
			// aapt resource value: 0x7f040019
			public const int use_hamlet_applet = 2130968601;
			
			// aapt resource value: 0x7f040017
			public const int vibrate = 2130968599;
			
			// aapt resource value: 0x7f040004
			public const int view_chat = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int view_game = 2130968579;
			
			// aapt resource value: 0x7f04000a
			public const int white = 2130968586;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int button_text = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
