#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LiveOthelloAndroid.Resource", IsApplication=true)]

namespace LiveOthelloAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int black_disc = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int buttonstyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int empty_disc = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int game = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int game_small = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_title_share_default = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int logo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int menu_info = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int menu_settings = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int menu_update = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int tournament_small = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int white_disc = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int btnGame = 2131099652;
			
			// aapt resource value: 0x7f060013
			public const int btnMenu = 2131099667;
			
			// aapt resource value: 0x7f06001d
			public const int btnMoveFirst = 2131099677;
			
			// aapt resource value: 0x7f060020
			public const int btnMoveLast = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int btnMoveNext = 2131099679;
			
			// aapt resource value: 0x7f06001e
			public const int btnMovePrior = 2131099678;
			
			// aapt resource value: 0x7f060014
			public const int btnViewChange = 2131099668;
			
			// aapt resource value: 0x7f060006
			public const int cbNotificationSound = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int cbNotificationVibration = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int cbUseLocalViewer = 2131099656;
			
			// aapt resource value: 0x7f060019
			public const int gameName = 2131099673;
			
			// aapt resource value: 0x7f060003
			public const int gamesspinner = 2131099651;
			
			// aapt resource value: 0x7f06001a
			public const int gridview = 2131099674;
			
			// aapt resource value: 0x7f060012
			public const int layoutButtons = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int layoutFlipper = 2131099669;
			
			// aapt resource value: 0x7f060005
			public const int layoutNews = 2131099653;
			
			// aapt resource value: 0x7f06001b
			public const int positionInfo = 2131099675;
			
			// aapt resource value: 0x7f060011
			public const int rbGamesEvery = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int rbGamesNone = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int rbGamesOne = 2131099664;
			
			// aapt resource value: 0x7f06000d
			public const int rbTournamentEvery = 2131099661;
			
			// aapt resource value: 0x7f06000b
			public const int rbTournamentNone = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int rbTournamentOne = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int rgGamesNotifications = 2131099662;
			
			// aapt resource value: 0x7f06000a
			public const int rgTournamentNotifications = 2131099658;
			
			// aapt resource value: 0x7f06001c
			public const int statusText = 2131099676;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int textView2 = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int textView3 = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int tournamentspinner = 2131099649;
			
			// aapt resource value: 0x7f060016
			public const int viewFlipper1 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int webView1 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int webView2 = 2131099672;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Settings = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ViewGame = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ViewGameNative = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int button_text = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
